spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recommender_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.projectrecommender: DEBUG
    org.flywaydb: DEBUG