INSERT INTO projects (title, description, tech_stack, difficulty, skills_required, domain, learning_outcomes, estimated_hours, portfolio_impact_score) VALUES

-- BACKEND PROJECTS
('Personal Finance Tracker API',
 'Build a RESTful API for tracking income, expenses, and budgets with user authentication and reporting.',
 'Java, Spring Boot, MySQL, JWT, REST API',
 'INTERMEDIATE',
 'Java, Spring Boot, MySQL, REST API, JWT',
 'Backend Development',
 'Master REST API design, JWT authentication, database modeling, and financial domain logic.',
 80, 7.5),

('URL Shortener Service',
 'Create a scalable URL shortening service like bit.ly with analytics and custom aliases.',
 'Java, Spring Boot, Redis, MySQL',
 'INTERMEDIATE',
 'Java, Spring Boot, Redis, MySQL, REST API',
 'Backend Development',
 'Learn caching with Redis, short code generation algorithms, and high-volume system design.',
 60, 7.0),

('API Rate Limiter Library',
 'Implement a configurable rate limiting middleware library for Spring Boot applications.',
 'Java, Spring Boot, Redis, AOP',
 'ADVANCED',
 'Java, Spring Boot, Redis, AOP, Design Patterns',
 'Backend Development',
 'Deep understanding of AOP, token bucket algorithms, distributed rate limiting, and library design.',
 100, 8.5),

('Job Queue System',
 'Build an async job processing system with worker threads, retry logic, and a dashboard.',
 'Java, Spring Boot, MySQL, WebSockets',
 'ADVANCED',
 'Java, Spring Boot, MySQL, Concurrency, WebSockets',
 'Backend Development',
 'Learn async processing, thread pools, job scheduling, and real-time status updates.',
 120, 8.0),

('E-Commerce Order Service',
 'Implement the order management microservice for an e-commerce platform with payment integration.',
 'Java, Spring Boot, MySQL, REST API',
 'INTERMEDIATE',
 'Java, Spring Boot, MySQL, REST API, Microservices',
 'Backend Development',
 'Understand order state machines, payment gateway integration, and microservice communication.',
 90, 8.0),

-- FULL-STACK PROJECTS
('AI Resume Analyzer',
 'Upload a resume PDF and get AI-powered feedback, ATS score, and improvement suggestions.',
 'Java, Spring Boot, React, OpenAI API, MySQL',
 'INTERMEDIATE',
 'Java, Spring Boot, React, OpenAI API, REST API',
 'AI/ML',
 'Integrate LLM APIs, handle file uploads, build responsive UI, and implement feedback loops.',
 100, 9.5),

('API Monitoring Dashboard',
 'Real-time dashboard to monitor API endpoints for uptime, latency, and error rates.',
 'Java, Spring Boot, React, MySQL, WebSockets, Chart.js',
 'INTERMEDIATE',
 'Java, Spring Boot, React, WebSockets, MySQL',
 'DevOps',
 'Learn real-time data streaming, charting libraries, alerting systems, and health checks.',
 110, 8.5),

('Student Peer Review Platform',
 'Platform where students submit assignments and give/receive structured peer feedback.',
 'Java, Spring Boot, React, MySQL',
 'INTERMEDIATE',
 'Java, Spring Boot, React, MySQL, REST API',
 'Web Development',
 'Practice role-based access control, workflow state management, and rich text editing.',
 90, 7.5),

('Expense Splitting App',
 'Group expense tracker like Splitwise — add members, record expenses, auto-calculate balances.',
 'Java, Spring Boot, React, MySQL',
 'INTERMEDIATE',
 'Java, Spring Boot, React, MySQL, REST API',
 'Web Development',
 'Learn graph-based debt resolution algorithms, real-time balance calculations, and group management.',
 80, 7.5),

('Recipe Recommendation Engine',
 'Input available ingredients and get recipe suggestions with nutritional info and substitutions.',
 'Java, Spring Boot, React, MySQL, OpenAI API',
 'INTERMEDIATE',
 'Java, Spring Boot, React, OpenAI API, MySQL',
 'AI/ML',
 'Practice recommendation algorithms, natural language parsing, and API integration.',
 85, 8.0),

-- FRONTEND PROJECTS
('Developer Portfolio Generator',
 'Generate a beautiful, customizable developer portfolio website from a JSON config.',
 'React, TypeScript, Tailwind CSS, GitHub API',
 'BEGINNER',
 'React, TypeScript, CSS, GitHub API',
 'Frontend Development',
 'Master component composition, responsive design, dynamic rendering, and API integration.',
 50, 7.0),

('Real-Time Collaborative Whiteboard',
 'Multi-user drawing canvas with real-time sync, shapes, and text tools.',
 'React, WebSockets, Canvas API, Spring Boot',
 'ADVANCED',
 'React, WebSockets, Canvas API, Spring Boot',
 'Frontend Development',
 'Learn WebSocket events, canvas manipulation, CRDT conflict resolution, and collaborative UX.',
 130, 9.0),

('Job Board Aggregator',
 'Scrape and aggregate job listings from multiple platforms with filters and alerts.',
 'React, TypeScript, Spring Boot, MySQL',
 'INTERMEDIATE',
 'React, TypeScript, Spring Boot, MySQL, REST API',
 'Web Development',
 'Practice web scraping, data normalization, search/filter UIs, and email notifications.',
 95, 8.0),

-- AI/ML PROJECTS
('Sentiment Analysis Tool',
 'Analyze sentiment of tweets, reviews, or text with a fine-tuned transformer model.',
 'Java, Spring Boot, Python, Hugging Face, React',
 'INTERMEDIATE',
 'Java, Spring Boot, Python, Machine Learning, REST API',
 'AI/ML',
 'Understand NLP pipelines, model serving, API design for ML, and evaluation metrics.',
 90, 8.5),

('AI Code Review Assistant',
 'GitHub bot that reviews pull requests and suggests improvements using OpenAI.',
 'Java, Spring Boot, GitHub API, OpenAI API',
 'ADVANCED',
 'Java, Spring Boot, GitHub API, OpenAI API, Webhooks',
 'AI/ML',
 'Learn webhook processing, prompt engineering, GitHub App development, and async review flows.',
 110, 9.5),

('Document Q&A System',
 'Upload documents and ask questions using RAG (Retrieval Augmented Generation).',
 'Java, Spring Boot, OpenAI API, React, MySQL',
 'ADVANCED',
 'Java, Spring Boot, OpenAI API, Vector Search, React',
 'AI/ML',
 'Implement RAG architecture, document chunking, vector storage, and conversational AI.',
 120, 9.5),

('Fake News Detector',
 'ML model to classify news articles as real or fake with confidence scores.',
 'Java, Spring Boot, Python, Scikit-learn, React',
 'INTERMEDIATE',
 'Java, Spring Boot, Python, Machine Learning, REST API',
 'AI/ML',
 'Practice classification models, feature engineering, model evaluation, and API serving.',
 85, 8.0),

-- DEVOPS PROJECTS
('CI/CD Pipeline Builder',
 'Web UI to configure and visualize CI/CD pipelines with GitHub integration.',
 'Java, Spring Boot, React, Docker, GitHub API',
 'ADVANCED',
 'Java, Spring Boot, React, Docker, GitHub API, DevOps',
 'DevOps',
 'Master pipeline stages, webhook triggers, Docker image builds, and deployment automation.',
 130, 9.0),

('Kubernetes Dashboard Clone',
 'Simplified Kubernetes cluster dashboard showing pod health, logs, and resource usage.',
 'Java, Spring Boot, React, Kubernetes API, Docker',
 'ADVANCED',
 'Java, Spring Boot, Kubernetes, Docker, React',
 'DevOps',
 'Deep dive into Kubernetes API, container orchestration, log streaming, and health monitoring.',
 140, 9.0),

('Infrastructure Cost Estimator',
 'Tool to estimate monthly cloud costs based on selected AWS services and usage.',
 'React, TypeScript, Spring Boot, MySQL',
 'INTERMEDIATE',
 'React, TypeScript, Spring Boot, MySQL, AWS',
 'DevOps',
 'Learn cloud pricing models, dynamic form generation, and cost optimization strategies.',
 70, 7.5),

-- DATABASE PROJECTS
('Database Schema Visualizer',
 'Connect to any MySQL/PostgreSQL database and generate interactive ER diagrams.',
 'Java, Spring Boot, React, JDBC, D3.js',
 'INTERMEDIATE',
 'Java, Spring Boot, SQL, JDBC, React, D3.js',
 'Database',
 'Master JDBC metadata APIs, graph rendering with D3, and schema introspection.',
 85, 8.0),

('Query Performance Analyzer',
 'Tool that analyzes slow SQL queries and suggests indexes and optimizations.',
 'Java, Spring Boot, MySQL, React',
 'ADVANCED',
 'Java, Spring Boot, SQL, MySQL, Performance Tuning',
 'Database',
 'Learn EXPLAIN plans, index strategy, query rewriting, and performance profiling.',
 100, 8.5),

-- SECURITY PROJECTS
('Password Manager API',
 'Secure password vault with AES encryption, master password, and browser extension.',
 'Java, Spring Boot, React, MySQL, AES Encryption',
 'INTERMEDIATE',
 'Java, Spring Boot, MySQL, Cryptography, REST API',
 'Security',
 'Implement AES encryption, PBKDF2 key derivation, secure vault design, and browser integration.',
 90, 8.5),

('OAuth2 Provider',
 'Build a custom OAuth2 authorization server with PKCE support and token management.',
 'Java, Spring Boot, Spring Security, MySQL',
 'ADVANCED',
 'Java, Spring Boot, Spring Security, OAuth2, JWT',
 'Security',
 'Deep understanding of OAuth2 flows, PKCE, token introspection, and authorization server design.',
 120, 9.0),

-- BEGINNER PROJECTS
('Student Grade Calculator',
 'Simple web app to input grades, compute GPA, and visualize grade distribution.',
 'React, TypeScript, CSS',
 'BEGINNER',
 'React, TypeScript, CSS',
 'Web Development',
 'Practice component state management, form handling, basic math logic, and chart rendering.',
 30, 5.0),

('Weather Dashboard',
 'Fetch and display weather data for any city using OpenWeatherMap API.',
 'React, REST API, CSS',
 'BEGINNER',
 'React, REST API, CSS, JavaScript',
 'Web Development',
 'Learn API consumption, async/await, conditional rendering, and responsive layouts.',
 25, 5.5),

('Task Manager App',
 'CRUD task manager with categories, priorities, due dates, and drag-and-drop reordering.',
 'React, TypeScript, Spring Boot, MySQL',
 'BEGINNER',
 'React, TypeScript, Spring Boot, MySQL',
 'Web Development',
 'Master CRUD operations, drag-and-drop UX, state management, and REST integration.',
 40, 6.0),

('Library Management System',
 'Manage books, members, and borrowing records with search and overdue notifications.',
 'Java, Spring Boot, MySQL, React',
 'BEGINNER',
 'Java, Spring Boot, MySQL, REST API',
 'Backend Development',
 'Practice entity relationships, CRUD APIs, search filtering, and scheduled notifications.',
 50, 6.0),

('CLI Note-Taking Tool',
 'Command-line app to create, list, search, and tag notes stored as local JSON files.',
 'Java, CLI, JSON',
 'BEGINNER',
 'Java, CLI, File I/O, JSON',
 'Backend Development',
 'Build practical CLI parsing, file I/O operations, JSON serialization, and search logic.',
 20, 4.5),

-- ADVANCED PROJECTS
('Distributed Caching System',
 'Implement a distributed key-value cache with consistent hashing and replication.',
 'Java, Spring Boot, Networking, MySQL',
 'ADVANCED',
 'Java, Spring Boot, Distributed Systems, Networking, Caching',
 'System Design',
 'Understand consistent hashing, replication strategies, CAP theorem, and distributed state.',
 150, 9.5),

('Microservices E-Commerce Platform',
 'Full e-commerce system with separate microservices for users, products, orders, and payments.',
 'Java, Spring Boot, Docker, MySQL, React, REST API',
 'ADVANCED',
 'Java, Spring Boot, Microservices, Docker, MySQL, React',
 'System Design',
 'Master inter-service communication, API gateway patterns, distributed transactions, and service discovery.',
 200, 10.0),

('Real-Time Chat Application',
 'Feature-complete chat app with rooms, direct messages, file sharing, and read receipts.',
 'Java, Spring Boot, WebSockets, React, MySQL',
 'INTERMEDIATE',
 'Java, Spring Boot, WebSockets, React, MySQL',
 'Web Development',
 'Learn bi-directional communication, message persistence, presence indicators, and file uploads.',
 100, 8.5),

('Blockchain Voting System',
 'Decentralized voting application with tamper-proof records and audit trails.',
 'Java, Spring Boot, Blockchain Concepts, React, MySQL',
 'ADVANCED',
 'Java, Spring Boot, Blockchain, Cryptography, React',
 'Security',
 'Understand blockchain fundamentals, Merkle trees, digital signatures, and audit trail design.',
 130, 9.0);
